# Buổi 3: Luyện tập với Numpy

In [1]:
v = list(range(1,6))
print(v)
print(2*v)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [2]:
import numpy as np

a = np.zeros((2,2))      # Create an array of all zeros
print(a)                 # Prints "[[0. 0.]
                         #          [0. 0.]]"

b = np.ones((1,2))       # Create an array of all ones
print(b)                 # Prints "[[1. 1.]]"

c = np.full((2,2), 7)    # Create a constant array
print(c)                 # Prints "[[7. 7.]
                         #          [7. 7.]]"

d = np.eye(2)            # Create a 2x2 identity matrix
print(d)                 # Prints "[[1. 0.]
                         #          [0. 1.]]"

e = np.random.random((2,2))   # Create an array filled with random values
print(e)                 # Might print "[[0.91940167 0.08143941]
                         #              [0.68744134 0.87236687]]"


[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.54783851 0.15232737]
 [0.0818858  0.76672997]]


In [3]:
import numpy as np
a = np.arange(15).reshape(3, 5)
print(a)
a = a.reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## Kết thúc