# Buổi 03: Luyện tập với Numpy _ Practice at home

## Phân tích và hiển thị dữ liệu

In [1]:
# list range: tạo ra sự khác biệt giữa chuỗi và numpy
v = list(range(1,6))
print(v)
print(2*v)
#

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [2]:
import numpy as np
v = np.arange(1,6)
print(v)
print(v*2)

[1 2 3 4 5]
[ 2  4  6  8 10]


#### Khi khai báo biến là biến Numpy thì Python sẽ hiểu đó không phải chỉ đơn thuần là chuỗi, Numpy có thể cộng trừ nhân chia và có hướng chứ không vô hướng

In [4]:
fruits = ["apple", "banana", "cherry"] #lists []
colors = ("red", "green", "blue") #tuples ()
animals = {'cat', 'dog'} #sets {}
person = {"name" : "Tom", "age" : 20} #dictionaries {}
print(fruits)
print(colors)
print(animals)
print(person)

['apple', 'banana', 'cherry']
('red', 'green', 'blue')
{'dog', 'cat'}
{'name': 'Tom', 'age': 20}


In [12]:

x = [60, 70, 80, 90]
#ĐỐi với dữ liệu dạng chuỗi, có thể lấy dữ liệu theo thứ tự, dạng tuple có thứ tự nên kiểm tra dữ liệu
print('len(x)=',len(x))
#Hàm len: đếm số ký tự có trong chuỗi: chuỗi ở đây có 4 số là 60,70,80,90
print('x[0]=',x[0])
print('x[1]=', x[1])
print('x[-1]=',x[-1])
print('x[1:3]=',x[1:3])
print('x[1:4]=',x[1:4])

len(x)= 4
x[0]= 60
x[1]= 70
x[-1]= 90
x[1:3]= [70, 80]
x[1:4]= [70, 80, 90]


In [16]:
from IPython.display import display
#Display không có sẵn mà phải import từ thư viện của Python vào
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
#Tương tự như việc nhân vector có hướng. Kết quả là 1 vector có hướng khác
print('c = ')
display(c)

c = 


array([ 4, 10, 18])

In [18]:
import numpy as np

a = np.zeros((2,2))
display(a)
#Tạo một ma trận vuông 2x2 với tất cả đều bằng 0

b = np.ones((3,2))
display(b)
#Tạo một ma trận 3 hàng, 2 cột với các phần tử đều bằng 1

c = np.full((4,5),7)
display(c)
#Tạo một ma trận 4 hàng 5 cột với các phần tử đều bằng 7

d = np.eye(4)
display(d)
#Tạo một ma trận, ma trận np.eye là ma trận đơn vị với 4 hàng 4 cột, đường chéo ma trận đơn vị luôn bằng 1, các phần tử còn lại sẽ bằng 0

e = np.random.random((2,2))
Tạo một ma trận ngẫu nhiên 2 hàng 2 cột, riên gma

display(e)

array([[0., 0.],
       [0., 0.]])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[0.92551762, 0.49944022],
       [0.31738184, 0.74994794]])

In [3]:

import numpy as np
a = np.arange(15, dtype=float)
display(a)
#np.range có nghĩa là tạo một mảng có 15 phần tử, dtype: xác định kiểu dữ liệu cần yêu cầu. Ở đây float là cần in ra kiểu dữ liệu là số nguyên

a = a.reshape(3,5)
display(a)
#Hàm reset có nghĩa là chuyển đổi, từ mảng thành một ma trận có 3 dòng 5 cột

display(a.shape)
#shape: cho biết kích thước của mảng dữ liệu, ở đây sẽ có kết quả là (3,5)

display(a.ndim)
#ndim: viết tắt của dimension nghĩa là số lượng hướng, ở đây có 2 hướng là dòng và cột

display(a.dtype)
#dtype: trả về kiểu dữ liệu của mảng, có thể là float64 hoặc float32

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

(3, 5)

2

dtype('float64')

In [7]:
import numpy as np
a = np.array([1,2,3,4,5,6])
display(a)

a=a.reshape(2,3)
display(a)






array([1, 2, 3, 4, 5, 6])

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
git push origin gh-pages --force

SyntaxError: invalid syntax (114163457.py, line 1)

## Kết thúc